### ISSUE TITLE
camera should be placed on latlon provided by the user

### ISSUE THREAD

**Issue by mgiraldo** [nypl-spacetime/surveyor#74] opened 2016-07-11 19:07 UTC

**Comment by bertspaan** [comment] 2017-05-08 18:48
duplicate of #116.

**Closed by bertspaan** 2017-05-08 18:48 UTC

**Comment by mgiraldo** [comment] 2017-05-08 18:52
116 was duplicate of this 😔

**Comment by bertspaan** [comment] 2017-05-08 18:56
I know................................................................................................................................... I made a big mistake.

**Comment by mgiraldo** [comment] 2017-05-08 18:57
ignoring my 10-month-old issues
